---
# File: tasks/main.yml - Main tasks for ansible-couchbase-server

- name: Variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if Couchbase Server is installed
  stat: path=/opt/couchbase/VERSION.txt
  register: v

# CentOS/RHEL tasks
- include: RedHat.yml
  when: not v.stat.exists and ansible_os_family == "RedHat"

# Debian/Ubuntu tasks
- include: Debian.yml
  when: not v.stat.exists and ansible_os_family == "Debian"

- name: Detect if we're running in a Docker container
  stat: path=/.dockerinit
  register: dockerinit

- name: Update user limits
  copy: src=etc_security_limits.d_couchbase-server.conf dest=/etc/security/limits.d/couchbase-server.conf owner=root group=root mode=0644

- name: Optimized settings for Couchbase Server data and index volumes
  mount: "name={{ couchbase_server_mountpoint }} src={{ couchbase_server_partition }} opts={{ couchbase_server_mount_options }} fstype={{ couchbase_server_filesystem }} state=mounted"
  when: couchbase_server_tune_disks

- name: Additional OS config
  template: src=etc_rc.local.j2 dest=/etc/rc.local owner=root group=root mode=0755
  notify: Source local settings
  when: couchbase_server_tune_disks

- name: Kernel settings dir
  file: dest=/etc/sysctl.d state=directory
  when: not dockerinit.stat.exists

- name: Kernel settings config
  template: src=etc_sysctl.d_couchbase-server.conf.j2 dest=/etc/sysctl.d/couchbase-server.conf owner=root group=root mode=0644
  notify: Update kernel settings
  when: not dockerinit.stat.exists

- name: Disable THP
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done' >> /etc/rc.local
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done' >> /etc/rc.local
  shell: for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done
  when: not dockerinit.stat.exists
